name = "Hunter'z Persistency Module";
picture = "\x\Hz\Hz_mod_persistency\media\Hunterz_logo.paa";
logo = "\x\Hz\Hz_mod_persistency\media\Hunterz_icon.paa";
logoOver = "\x\Hz\Hz_mod_persistency\media\Hunterz_icon.paa";
logoSmall = "\x\Hz\Hz_mod_persistency\media\Hunterz_iconSmall.paa";
actionName = "Website";
action = "https://github.com/KHunter-Arma";
author = "K.Hunter";
overviewPicture = "\x\Hz\Hz_mod_persistency\media\Hunterz_logo.paa";
